version: "2"

linters:
  default: none
  enable:
    - errcheck     # unchecked errors
    - govet        # suspicious code patterns
    - staticcheck  # comprehensive static analysis
    - gosimple     # code simplification suggestions
    - unused       # unused code
    - gosec        # security issues
